import Head from 'next/head'
import { useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const [code, setCode] = useState("");
  const router = useRouter();

  const onSubmit = (e: any) => {
    e.preventDefault();
    router.push("/room/"+code)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className='h-screen flex justify-center items-center'>
        <form onSubmit={onSubmit} action="" className='flex flex-col gap-6 justify-center items-center'>
          <div className='flex flex-col gap-2'>
            <label className='text-sm' htmlFor="room">Enter Room Code:</label>
            <input className='text-black' type="text" name="room" id="room" onChange={(e) => setCode(e.target.value)} />
          </div>
          <button className='bg-blue-900 px-6 py-1 rounded-sm' type="submit">Submit</button>
        </form>
      </main>
    </>
  )
}
